version: '3'
services:
  jekyll:
      image: jekyll/jekyll:4
      environment:
        - JEKYLL_ENV=development
      command: /srv/jekyll/run.sh
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll:cached
          - ./vendor/bundle:/usr/local/bundle:cached
